name: Deploy to Firebase

on:
  push:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i && npm run build
      # now deploy to firebase
      - name: Deploy site
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHARE_MY_TEXT }}"
          projectId: sharemytext
          channelId: live
